"""PDF report renderer — Jinja2 HTML template to PDF via Playwright."""

import io
import logging
import os
from typing import Optional

from jinja2 import Template

logger = logging.getLogger(__name__)

REPORT_HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{{ client_name }} — SEO Report {{ report_month }}</title>
<style>
  body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; color: #333; }
  h1 { color: #1a1a2e; border-bottom: 3px solid #0066cc; padding-bottom: 10px; }
  h2 { color: #0066cc; margin-top: 30px; }
  .metric-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin: 20px 0; }
  .metric-card { background: #f8f9fa; border-radius: 8px; padding: 20px; text-align: center; }
  .metric-value { font-size: 2em; font-weight: bold; color: #0066cc; }
  .metric-label { color: #666; font-size: 0.9em; margin-top: 5px; }
  .alert { background: #fff3cd; border-left: 4px solid #ffc107; padding: 12px 16px; margin: 10px 0; }
  .alert.critical { background: #f8d7da; border-left-color: #dc3545; }
  .summary { background: #f8f9fa; padding: 20px; border-radius: 8px; line-height: 1.6; }
  table { width: 100%; border-collapse: collapse; margin: 15px 0; }
  th { background: #0066cc; color: white; padding: 10px; text-align: left; }
  td { padding: 8px 10px; border-bottom: 1px solid #eee; }
  tr:nth-child(even) { background: #f8f9fa; }
  .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; text-align: center; color: #999; }
</style>
</head>
<body>
<h1>{{ client_name }} — Monthly SEO Report</h1>
<p>Report Period: {{ report_month }}</p>

<div class="metric-grid">
  <div class="metric-card">
    <div class="metric-value">{{ traffic.total_sessions | default(0) | int }}</div>
    <div class="metric-label">Organic Sessions</div>
  </div>
  <div class="metric-card">
    <div class="metric-value">{{ search.total_clicks | default(0) | int }}</div>
    <div class="metric-label">Search Clicks</div>
  </div>
  <div class="metric-card">
    <div class="metric-value">{{ search.avg_ctr | default(0) }}%</div>
    <div class="metric-label">Average CTR</div>
  </div>
  <div class="metric-card">
    <div class="metric-value">{{ traffic.conversions | default(0) | int }}</div>
    <div class="metric-label">Conversions</div>
  </div>
  <div class="metric-card">
    <div class="metric-value">{{ search.avg_position | default('—') }}</div>
    <div class="metric-label">Avg Position</div>
  </div>
  <div class="metric-card">
    <div class="metric-value">{{ indexation.indexed | default(0) }}</div>
    <div class="metric-label">Pages Indexed</div>
  </div>
</div>

{% if anomalies %}
<h2>Alerts</h2>
{% for alert in anomalies %}
<div class="alert {{ 'critical' if alert.severity == 'critical' else '' }}">
  <strong>{{ alert.alert_type | replace('_', ' ') | title }}:</strong> {{ alert.detail }}
</div>
{% endfor %}
{% endif %}

<h2>Executive Summary</h2>
<div class="summary">{{ summary | safe }}</div>

<h2>Content Pipeline</h2>
<table>
  <tr><th>Status</th><th>Count</th></tr>
  {% for status, count in content.items() %}
  <tr><td>{{ status | title }}</td><td>{{ count }}</td></tr>
  {% endfor %}
</table>

<h2>Technical Health</h2>
<table>
  <tr><th>Priority</th><th>Issues</th></tr>
  {% for priority, count in technical.by_priority.items() %}
  <tr><td>{{ priority | title }}</td><td>{{ count }}</td></tr>
  {% endfor %}
</table>

<div class="footer">
  Generated by Chatterbuzz SEO Platform
</div>
</body>
</html>"""


def render_report_html(
    client_name: str,
    report_month: str,
    metrics: dict,
    anomalies: list[dict],
    summary: str,
) -> str:
    """Render the report as HTML."""
    template = Template(REPORT_HTML_TEMPLATE)
    return template.render(
        client_name=client_name,
        report_month=report_month,
        traffic=metrics.get("organic_traffic", {}),
        search=metrics.get("search_performance", {}),
        content=metrics.get("content_metrics", {}),
        technical=metrics.get("technical_health", {}),
        indexation=metrics.get("indexation", {}),
        anomalies=anomalies,
        summary=summary.replace("\n", "<br>"),
    )


async def render_pdf(html: str) -> bytes:
    """Convert HTML to PDF using Playwright.

    Requires: pip install playwright && playwright install chromium
    """
    try:
        from playwright.async_api import async_playwright

        async with async_playwright() as p:
            browser = await p.chromium.launch()
            page = await browser.new_page()
            await page.set_content(html, wait_until="networkidle")
            pdf_bytes = await page.pdf(
                format="A4",
                margin={"top": "20mm", "bottom": "20mm", "left": "15mm", "right": "15mm"},
                print_background=True,
            )
            await browser.close()
            return pdf_bytes
    except ImportError:
        logger.error("Playwright not installed. Install with: pip install playwright && playwright install chromium")
        raise
